# PRE-DEV DNN

| Setting | Value |
| ------ | ------ |
| Optimizer | Adam |
| Layer-in | in=10 out=8 actication=relu |
| Layer-out | in=8 out=3 actication=softmax |
| D-Value | 5.847|

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
# load Data
train_x = np.load('/home/spokencall/data/data4Tensor/train_x.npy')
train_y = np.load('/home/spokencall/data/data4Tensor/train_y.npy')
test_x = np.load('/home/spokencall/data/data4Tensor//test_x.npy')
test_y = np.load('/home/spokencall/data/data4Tensor/test_y.npy')
test_label = np.load('/home/spokencall/data/data4Tensor/originalY/test_y.npy')

In [12]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

In [13]:
removedFromTrain = 0
clean_train_x = np.array([]).reshape(0, 10)
clean_train_y = np.array([]).reshape(0, 3)

for idx, array in enumerate(train_x):
    shouldBeRemoved = False
    for data in array:
        if np.isinf(data):
            shouldBeRemoved = True
    if shouldBeRemoved:
        removedFromTrain += 1
    else:
        clean_train_x = np.vstack((clean_train_x, array))
        clean_train_y = np.vstack((clean_train_y, train_y[idx])) 

print('Finish cleaning Train Data.')
print('Removed datapoints:  ' + str(removedFromTrain))
print('length of train_x:   ' + str(len(clean_train_x)))
print('length of train_y:   ' + str(len(clean_train_y)))


clean_test_x = np.array([]).reshape(0, 10)
clean_test_y = np.array([]).reshape(0, 3)
clean_label = np.array([]).reshape(0, 1)
removedFromTest = 0
for idx, array in enumerate(test_x):
    shouldBeRemoved = False
    for data in array:
        if np.isinf(data):
            shouldBeRemoved = True
        
    if shouldBeRemoved:
        removedFromTest += 1
    else:
        clean_test_x = np.vstack((clean_test_x, array))
        clean_test_y = np.vstack((clean_test_y, test_y[idx]))
        clean_label = np.vstack((clean_label, test_label[idx]))

print('Finish cleaning Test Data.')
print('Removed datapoints:   ' + str(removedFromTest))
print('length of test_x:   ' + str(len(clean_test_x)))
print('length of test_y:   ' + str(len(clean_test_y)))
print('length of labels:   ' + str(len(clean_label)))

Finish cleaning Train Data.
Removed datapoints:  2
length of train_x:   10362
length of train_y:   10362
Finish cleaning Test Data.
Removed datapoints:   4
length of test_x:   1107
length of test_y:   1107
length of labels:   1107


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_train_x = sc.fit_transform(clean_train_x)
scaled_test_x = sc.transform(clean_test_x)

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [16]:
#Initializing Neural Network
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(8,activation = 'relu', input_dim = 10))

# Adding the output layer
classifier.add(Dense(3, activation = 'softmax'))

In [17]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [18]:
# Fitting our model 
classifier.fit(scaled_train_x, clean_train_y, batch_size = 5, epochs = 200)

Epoch 1/200
10362/10362 [==============================] - 2s 223us/step - loss: 0.4746 - acc: 0.8117
Epoch 2/200
10362/10362 [==============================] - 2s 203us/step - loss: 0.3838 - acc: 0.8496
Epoch 3/200
10362/10362 [==============================] - 2s 200us/step - loss: 0.3741 - acc: 0.8559
Epoch 4/200
10362/10362 [==============================] - 2s 198us/step - loss: 0.3690 - acc: 0.8630
Epoch 5/200
10362/10362 [==============================] - 2s 199us/step - loss: 0.3653 - acc: 0.8648
Epoch 6/200
10362/10362 [==============================] - 2s 199us/step - loss: 0.3630 - acc: 0.8660
Epoch 7/200
10362/10362 [==============================] - 2s 198us/step - loss: 0.3608 - acc: 0.8656
Epoch 8/200
10362/10362 [==============================] - 2s 202us/step - loss: 0.3598 - acc: 0.8650
Epoch 9/200
10362/10362 [==============================] - 2s 201us/step - loss: 0.3575 - acc: 0.8645
Epoch 10/200
10362/10362 [==============================] - 2s 198us/step - loss: 

10362/10362 [==============================] - 3s 257us/step - loss: 0.3318 - acc: 0.8741
Epoch 160/200
10362/10362 [==============================] - 3s 281us/step - loss: 0.3319 - acc: 0.8747
Epoch 161/200
10362/10362 [==============================] - 3s 254us/step - loss: 0.3322 - acc: 0.8735
Epoch 162/200
10362/10362 [==============================] - 3s 270us/step - loss: 0.3315 - acc: 0.8734
Epoch 163/200
10362/10362 [==============================] - 3s 260us/step - loss: 0.3320 - acc: 0.8725
Epoch 164/200
10362/10362 [==============================] - 3s 267us/step - loss: 0.3315 - acc: 0.8740
Epoch 165/200
10362/10362 [==============================] - 3s 260us/step - loss: 0.3322 - acc: 0.8735
Epoch 166/200
10362/10362 [==============================] - 3s 270us/step - loss: 0.3316 - acc: 0.8731
Epoch 167/200
10362/10362 [==============================] - 3s 258us/step - loss: 0.3315 - acc: 0.8737
Epoch 168/200
10362/10362 [==============================] - 3s 276us/step - l

In [20]:
# Save the model
#model_json = classifier..to_json()
#with open("sim_dnn_adam.json", "w+") as json_file:
#    json_file.write(model_json)
    
# serialize weights to HDF5
#classifier.save_weights("sim_dnn_adam.h5")

#print("Saved model to disk")

In [21]:
# Creating prediction
y_pred = classifier.predict(scaled_test_x)

In [22]:
output = np.array([]).reshape(0, 3)

for data in y_pred:
    prop1 = data[0]
    prop2 = data[1]
    prop3 = data[2]
    if prop1 > prop2 > prop3 or  prop1 > prop3 > prop2:
        output = np.vstack((output, [1, 0,0]))
    elif prop2 > prop1 > prop3 or prop2 > prop3 > prop1:
        output = np.vstack((output, [0, 1,0]))
    elif prop3 > prop1 > prop2 or prop3 > prop2 > prop1:
        output = np.vstack((output, [0, 0,1]))

output[78]

array([0., 0., 1.])

In [23]:
# [1 0 0] -> lang & me
# [0 1 0] -> me
# [0 0 1] -> nothing
CR, CA, PFA, GFA, FR, k = 0, 0, 0, 0, 0, 3.0
for idx, data in enumerate(output):
    # the students answer is correct in meaning and language
    # the system says the same -> accept
    if clean_label[idx] == 1 and np.array_equal(data,[1, 0, 0]):
        CA += 1
    # the system says correct meaning wrong language -> reject
    elif clean_label[idx] == 1 and np.array_equal(data,[0, 1, 0]):
        FR += 1
    # the system says incorrect meaning and incorrect language -> reject
    elif clean_label[idx] == 1 and np.array_equal(data,[0, 0, 1]):
        FR += 1
        
    # students answer is correct in meaning and wrong in language
    #The system says the same -> reject
    elif clean_label[idx] == 2 and np.array_equal(data,[0, 1, 0]):
        CR += 1
    # the system says correct meaning and correct language -> accept
    elif clean_label[idx] == 2 and np.array_equal(data,[1, 0, 0]):
        PFA += 1
    # the system says incorrect meaning and incorrect language -> reject
    elif clean_label[idx] == 2 and np.array_equal(data,[0, 0, 1]):
        CR += 1
    
    # students answer is incorrect in meaning and incorrect in language
    # the system says the same -> reject
    elif clean_label[idx] == 3 and np.array_equal(data,[0, 0, 1]):
        CR += 1
    # the system says correct meaning correct language -> accept
    elif clean_label[idx] == 3 and np.array_equal(data,[1, 0, 0]): 
        GFA += 1
    # the system says correct meaning incorrect language -> reject
    elif clean_label[idx] == 3 and np.array_equal(data,[0, 1, 0]):
        CR += 1

FA = PFA + k * GFA
Correct = CA + FR
Incorrect = CR + GFA + PFA
IncorrectRejectionRate = CR / ( CR + FA + 0.0 )
CorrectRejectionRate = FR / ( FR + CA + 0.0 )
print('\nINCORRECT UTTERANCES (' + str(Incorrect) + ')' )
print('CorrectReject    ' + str(CR) )
print('GrossFalseAccept ' + str(GFA) + '*' + str(k) + ' = ' + str(GFA * k) )
print('PlainFalseAccept ' + str(PFA) )
print('RejectionRate    ' + "{:.3f}".format(IncorrectRejectionRate) )

print('\nCORRECT UTTERANCES (' + str(Correct) + ')')
print('CorrectAccept    ' + str(CA) )
print('FalseReject      ' + str(FR) )
print('RejectionRate    ' + "{:.3f}".format(CorrectRejectionRate) )
print('\nD              ' +  "{:.3f}".format(IncorrectRejectionRate / CorrectRejectionRate) )


INCORRECT UTTERANCES (286)
CorrectReject    236
GrossFalseAccept 9*3.0 = 27.0
PlainFalseAccept 41
RejectionRate    0.776

CORRECT UTTERANCES (821)
CorrectAccept    712
FalseReject      109
RejectionRate    0.133

D              5.847
